### ISSUE TITLE
How to use it in ROS noetic?

### ISSUE THREAD

**Issue by LBJjames23** [ENPH353/enph353_gym-gazebo-noetic#1]
Hi, the ROS related dependencies:
sudo apt-get install \
python-pip python3-vcstool python3-pyqt4 \
pyqt5-dev-tools \
libbluetooth-dev libspnav-dev \
pyqt4-dev-tools libcwiid-dev \
cmake gcc g++ qt4-qmake libqt4-dev \
libusb-dev libftdi-dev \
python3-defusedxml python3-vcstool \
ros-melodic-octomap-msgs        \
ros-melodic-joy                 \
ros-melodic-geodesy             \
ros-melodic-octomap-ros         \
ros-melodic-control-toolbox     \
ros-melodic-pluginlib	       \
ros-melodic-trajectory-msgs     \
ros-melodic-control-msgs	       \
ros-melodic-std-srvs 	       \
ros-melodic-nodelet	       \
ros-melodic-urdf		       \
ros-melodic-rviz		       \
ros-melodic-kdl-conversions     \
ros-melodic-eigen-conversions   \
ros-melodic-tf2-sensor-msgs     \
ros-melodic-pcl-ros \
ros-melodic-navigation \
ros-melodic-sophus

It's related with ROSmelodic, how can I run it in ROS noetic?

**Comment by ENPH353** [comment]
Are you running this in Ubuntu 20.04? It looks to me you are running on Ubuntu 18.04 (and therefore the ros-melodic* packages). All my packages are using ROS Noetic.
